#game_logic/settings.py

#dimemsion de la ventana 
#------------------------------

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600


#colores
#------------------------------
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

#configuracion del jugador
#------------------------------
PLAYER_SPEED = 5 # PIXELES QUE SEMUEVE LA NAVE POR CADA CICLO DE JUEGO
#enemigos
ENEMY_SPEED = 2 # PIXELES QUE SEMUEVE EL ENEMIGO POR CADA CICLO DE JUEGO

#disparos
BULLET_SPEED = 10 # PIXELES QUE SE MUEVE EL DISPARO POR CADA CICLO DE JUEGO


#----CONFIGURACION PARA VISION POR cOMPUTADORA (CV)-------
#------TAMAÑO DE VIDEP QUE ESPERAMOS

CAM_WIDTH = 640
CAM_HEIGHT = 480

#RANGO DE COLOR PARA DETECCION DE OBJETOS (EN ESPACIO HSV) DETETECION DEL AVION
#HSV (HUE, SATURATION, VALUE)
#USAMOS UN RANGO  BAJO DE ROJP(H:0-10) Y UN RANGO ALTO DE ROJO (H:170-180)
RED_LOWER = (0, 100, 100)
RED_UPPER = (10, 255, 255)